---
# tasks file for bootstrap_salt for Debian system
- name: Add apt key for Debian
  apt_key:
    url: https://repo.saltstack.com/apt/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/amd64/latest/SALTSTACK-GPG-KEY.pub
    state: present
  become: "yes"
  when: ansible_distribution == "Debian"

- name: Add apt repo for Debian
  copy:
    dest: /etc/apt/sources.list.d/saltstack.list
    content: |
      deb http://repo.saltstack.com/apt/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/amd64/latest {{ ansible_distribution_release }} main
  become: "yes"
  when: ansible_distribution == "Debian"

- name: Install via Apt
  apt:
    name: salt-minion
    state: present
    update_cache: "yes"
  become: "yes"
  notify:
    - configure salt-minion
    - restart salt-minion
