---
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ubun-xenial
    box: ubuntu/xenial64
  - name: debian
    box: debian/stretch64
  - name: fedora
    box: generic/fedora27
  - name: centos
    box: centos/7
  - name: freebsd
    box: generic/freebsd11
provisioner:
  name: ansible
  inventory:
    host_vars:
      freebsd:
        ansible_python_interpreter: /usr/local/bin/python2.7
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
